/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dlu.bai1.view;

/**
 *
 * @author coder6622
 */
public class FormStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent
     */
    public FormStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnTitle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnForm = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        pnTable = new javax.swing.JPanel();
        pnBtn = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/Person-Male-Light-icon-24.png"))); // NOI18N
        pnTitle.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Quản Lý Sinh Viên");
        pnTitle.add(jLabel4);

        getContentPane().add(pnTitle, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        pnForm.setLayout(new javax.swing.BoxLayout(pnForm, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel1.setLayout(new java.awt.BorderLayout(16, 0));

        jLabel1.setText("Mã SV:");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 31));
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel1.add(jTextField1, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/search-icon-24.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jPanel1.add(jButton1, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel7.setLayout(new java.awt.BorderLayout(16, 0));

        jLabel8.setText("Họ Tên:");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 31));
        jPanel7.add(jLabel8, java.awt.BorderLayout.WEST);
        jPanel7.add(jTextField6, java.awt.BorderLayout.CENTER);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/new-icon-16.png"))); // NOI18N
        jButton10.setText("Nhập mới");
        jButton10.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel7.add(jButton10, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel8.setLayout(new java.awt.BorderLayout(16, 0));

        jLabel9.setText("Email: ");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 31));
        jPanel8.add(jLabel9, java.awt.BorderLayout.WEST);
        jPanel8.add(jTextField7, java.awt.BorderLayout.CENTER);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/Save-icon.png"))); // NOI18N
        jButton11.setText("Lưu");
        jButton11.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel8.add(jButton11, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel8);

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel13.setLayout(new java.awt.BorderLayout(16, 0));

        jLabel10.setText("Giới tính:");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 31));
        jPanel13.add(jLabel10, java.awt.BorderLayout.WEST);
        jPanel13.add(jTextField8, java.awt.BorderLayout.CENTER);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/Question-Help-icon-16.png"))); // NOI18N
        jButton12.setText("Cập nhật");
        jButton12.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel13.add(jButton12, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel14.setLayout(new java.awt.BorderLayout(16, 0));

        jLabel11.setText("Địa chỉ: ");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 31));
        jPanel14.add(jLabel11, java.awt.BorderLayout.WEST);
        jPanel14.add(jTextField9, java.awt.BorderLayout.CENTER);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/Button-Close-icon-16.png"))); // NOI18N
        jButton13.setText("Xóa");
        jButton13.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel14.add(jButton13, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel14);

        jPanel2.add(pnForm, java.awt.BorderLayout.PAGE_START);

        pnTable.setLayout(new java.awt.BorderLayout());

        jButton6.setText("jButton6");
        pnBtn.add(jButton6);

        jButton7.setText("jButton6");
        pnBtn.add(jButton7);

        jButton8.setText("jButton6");
        pnBtn.add(jButton8);

        jButton9.setText("jButton6");
        pnBtn.add(jButton9);

        pnTable.add(pnBtn, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnTable, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pnBtn;
    private javax.swing.JPanel pnForm;
    private javax.swing.JPanel pnTable;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables
}
