/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dlu.bai1.view;

/**
 *
 * @author coder6622
 */
public class FormStudent1 extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent1
     */
    public FormStudent1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnForm = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(880, 140));
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar-background-icon.png"))); // NOI18N
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Quản Lý Sinh Viên");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setMinimumSize(new java.awt.Dimension(880, 462));
        jPanel3.setLayout(new java.awt.BorderLayout());

        pnForm.setMinimumSize(new java.awt.Dimension(880, 462));
        pnForm.setLayout(new javax.swing.BoxLayout(pnForm, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel4.setMinimumSize(new java.awt.Dimension(880, 77));
        jPanel4.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1, java.awt.BorderLayout.WEST);

        jTextField1.setText("jTextField1");
        jPanel4.add(jTextField1, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jPanel4.add(jButton1, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel5.setMinimumSize(new java.awt.Dimension(880, 77));
        jPanel5.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel4.setText("jLabel1");
        jPanel5.add(jLabel4, java.awt.BorderLayout.WEST);

        jTextField2.setText("jTextField1");
        jPanel5.add(jTextField2, java.awt.BorderLayout.CENTER);

        jButton2.setText("jButton1");
        jPanel5.add(jButton2, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel6.setMinimumSize(new java.awt.Dimension(880, 77));
        jPanel6.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel5.setText("jLabel1");
        jPanel6.add(jLabel5, java.awt.BorderLayout.WEST);

        jTextField3.setText("jTextField1");
        jPanel6.add(jTextField3, java.awt.BorderLayout.CENTER);

        jButton3.setText("jButton1");
        jPanel6.add(jButton3, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel7.setMinimumSize(new java.awt.Dimension(880, 77));
        jPanel7.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel6.setText("jLabel1");
        jPanel7.add(jLabel6, java.awt.BorderLayout.WEST);

        jTextField4.setText("jTextField1");
        jPanel7.add(jTextField4, java.awt.BorderLayout.CENTER);

        jButton4.setText("jButton1");
        jPanel7.add(jButton4, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel8.setMinimumSize(new java.awt.Dimension(880, 77));
        jPanel8.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel7.setText("jLabel1");
        jPanel8.add(jLabel7, java.awt.BorderLayout.WEST);

        jTextField5.setText("jTextField1");
        jPanel8.add(jTextField5, java.awt.BorderLayout.CENTER);

        jButton5.setText("jButton1");
        jPanel8.add(jButton5, java.awt.BorderLayout.EAST);

        pnForm.add(jPanel8);

        jPanel3.add(pnForm, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton6.setText("jButton6");
        jPanel9.add(jButton6);

        jButton7.setText("jButton6");
        jPanel9.add(jButton7);

        jButton8.setText("jButton6");
        jPanel9.add(jButton8);

        jButton9.setText("jButton6");
        jPanel9.add(jButton9);

        jPanel2.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel pnForm;
    // End of variables declaration//GEN-END:variables
}
