/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dlu.edu.view;

/**
 *
 * @author coder6622
 */
public class FormStudent1 extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent1
     */
    public FormStudent1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSex = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnForm = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMinimumSize(new java.awt.Dimension(880, 175));
        jPanel2.setPreferredSize(new java.awt.Dimension(880, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Student-3-icon.png"))); // NOI18N
        jLabel3.setText("Quản Lý Sinh Viên");
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        pnForm.setLayout(new javax.swing.BoxLayout(pnForm, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel1.setLayout(new java.awt.BorderLayout(32, 0));

        jLabel2.setText("Mã SV:");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel1.add(jLabel2, java.awt.BorderLayout.WEST);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon-24.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jPanel1.add(jButton1, java.awt.BorderLayout.EAST);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jTextField1.setMargin(new java.awt.Insets(2, 6, 2, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 15));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 15));
        jPanel13.add(jTextField1);

        jPanel14.setPreferredSize(new java.awt.Dimension(300, 22));
        jPanel13.add(jPanel14);

        jPanel1.add(jPanel13, java.awt.BorderLayout.CENTER);

        pnForm.add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel4.setLayout(new java.awt.BorderLayout(32, 0));

        jLabel4.setText("Họ Tên:");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel4.add(jLabel4, java.awt.BorderLayout.WEST);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-icon-16.png"))); // NOI18N
        jButton2.setText("Nhập mới");
        jButton2.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel4.add(jButton2, java.awt.BorderLayout.EAST);
        jPanel4.add(jTextField2, java.awt.BorderLayout.CENTER);

        pnForm.add(jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel8.setLayout(new java.awt.BorderLayout(32, 0));

        jLabel7.setText("Email:");
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel8.add(jLabel7, java.awt.BorderLayout.WEST);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        jButton5.setText("Lưu");
        jButton5.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel8.add(jButton5, java.awt.BorderLayout.EAST);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));
        jPanel11.add(jTextField5);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 16, 1, 1));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("Số ĐT:");
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 16));
        jPanel12.add(jLabel10, java.awt.BorderLayout.WEST);
        jPanel12.add(jTextField8, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12);

        jPanel8.add(jPanel11, java.awt.BorderLayout.CENTER);

        pnForm.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel9.setLayout(new java.awt.BorderLayout(32, 0));

        jLabel8.setText("Giới Tính:");
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel9.add(jLabel8, java.awt.BorderLayout.WEST);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-edit-icon-16.png"))); // NOI18N
        jButton6.setText("Cập nhật");
        jButton6.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel9.add(jButton6, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(64, 22));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnGroupSex.add(jRadioButton1);
        jRadioButton1.setText("Nam");
        jPanel6.add(jRadioButton1);

        btnGroupSex.add(jRadioButton2);
        jRadioButton2.setText("Nữ");
        jPanel6.add(jRadioButton2);

        jPanel9.add(jPanel6, java.awt.BorderLayout.CENTER);

        pnForm.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel10.setLayout(new java.awt.BorderLayout(32, 0));

        jLabel9.setText("Địa chỉ: ");
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel10.add(jLabel9, java.awt.BorderLayout.WEST);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-edit-delete-icon-16.png"))); // NOI18N
        jButton7.setText("Xóa");
        jButton7.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel10.add(jButton7, java.awt.BorderLayout.EAST);
        jPanel10.add(jTextField7, java.awt.BorderLayout.CENTER);

        pnForm.add(jPanel10);

        jPanel3.add(pnForm, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-First-icon-48.png"))); // NOI18N
        jPanel7.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Skip-backward-icon2-48.png"))); // NOI18N
        jPanel7.add(jButton4);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fast-forward-icon-48.png"))); // NOI18N
        jPanel7.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Last-icon-48.png"))); // NOI18N
        jPanel7.add(jButton9);

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel pnForm;
    // End of variables declaration//GEN-END:variables
}
