/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dlu.edu.view;

import dlu.edu.model.StudentModelTable;
import dlu.edu.model.Student;
import java.awt.event.ActionListener;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author coder6622
 */
public class FormStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent
     */
    StudentModelTable studentModelTable;

    public FormStudent() {
        studentModelTable = new StudentModelTable();
        initComponents();
    }

    public void showStudents(List<Student> students) {
        studentModelTable.setData(students);
        if (jtableStudent != null && jtableStudent.getRowCount() > 0) {
            jtableStudent.getSelectionModel().setSelectionInterval(0, 0);
        }
    }

    public void addTableSelectionListener(ListSelectionListener listener) {
        jtableStudent.getSelectionModel().addListSelectionListener(listener);
    }

    public void addAddStudentListener(ActionListener listener) {
        btnSave.addActionListener(listener);
    }

    public void addRemoveStudentListener(ActionListener listener) {
        btnDelete.addActionListener(listener);
    }

    public void addEditStudentListener(ActionListener listener) {
        btnEdit.addActionListener(listener);
    }

    public Student getStudentData() {

        String masv = txtMaSV.getText();
        String ten = txtHoTen.getText();
        String email = txtEmail.getText();
        String soDt = txtSoDT.getText();
        String diaChi = txtDiaChi.getText();
        int gioiTinh = rdNam.isSelected() ? 1 : 0;
        return new Student(masv, ten, email, soDt, diaChi, gioiTinh);
    }

    public void fillInputForm() {
        int row = jtableStudent.getSelectedRow();

        if (row >= 0) {
            txtMaSV.setText(jtableStudent.getValueAt(row, 0).toString());
            txtHoTen.setText(jtableStudent.getValueAt(row, 1).toString());
            txtEmail.setText(jtableStudent.getValueAt(row, 2).toString());
            txtSoDT.setText(jtableStudent.getValueAt(row, 3).toString());
            txtDiaChi.setText(jtableStudent.getValueAt(row, 4).toString());
            if (Integer.parseInt(jtableStudent.getValueAt(row, 5).toString()) == 1) {
                rdNam.setSelected(true);
            } else {
                rdNu.setSelected(true);
            }
        }
    }

    public void showMessag(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSex = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnMa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        pnTen = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtHoTen = new javax.swing.JTextField();
        pnEmailSDT = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableStudent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Student-3-icon.png"))); // NOI18N
        jLabel1.setText("Quản Lý Sinh Viên");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        pnMa.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        pnMa.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel2.setText("Mã SV:");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 22));
        pnMa.add(jLabel2, java.awt.BorderLayout.WEST);

        txtMaSV.setPreferredSize(new java.awt.Dimension(32, 22));
        pnMa.add(txtMaSV, java.awt.BorderLayout.CENTER);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon-24.png"))); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        pnMa.add(btnSearch, java.awt.BorderLayout.EAST);

        jPanel4.add(pnMa);

        pnTen.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        pnTen.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel3.setText("Họ Tên:");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 22));
        pnTen.add(jLabel3, java.awt.BorderLayout.WEST);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-icon-16.png"))); // NOI18N
        btnAdd.setText("Nhập mới");
        btnAdd.setPreferredSize(new java.awt.Dimension(108, 31));
        pnTen.add(btnAdd, java.awt.BorderLayout.EAST);
        pnTen.add(txtHoTen, java.awt.BorderLayout.CENTER);

        jPanel4.add(pnTen);

        pnEmailSDT.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        pnEmailSDT.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel4.setText("Email:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 22));
        pnEmailSDT.add(jLabel4, java.awt.BorderLayout.WEST);
        pnEmailSDT.add(jTextField3, java.awt.BorderLayout.CENTER);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setPreferredSize(new java.awt.Dimension(108, 31));
        pnEmailSDT.add(btnSave, java.awt.BorderLayout.EAST);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(txtEmail);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 24, 1, 1));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Số ĐT:");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel5.add(jLabel7, java.awt.BorderLayout.WEST);
        jPanel5.add(txtSoDT, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        pnEmailSDT.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.add(pnEmailSDT);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel7.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel5.setText("Giới tính:");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel7.add(jLabel5, java.awt.BorderLayout.WEST);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-edit-icon-16.png"))); // NOI18N
        btnEdit.setText("Cập nhật");
        btnEdit.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel7.add(btnEdit, java.awt.BorderLayout.EAST);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnGroupSex.add(rdNam);
        rdNam.setText("Nam");
        jPanel6.add(rdNam);

        btnGroupSex.add(rdNu);
        rdNu.setText("Nữ");
        jPanel6.add(rdNu);

        jPanel7.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 24, 8, 24));
        jPanel8.setLayout(new java.awt.BorderLayout(24, 0));

        jLabel6.setText("Địa chỉ:");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel8.add(jLabel6, java.awt.BorderLayout.WEST);
        jPanel8.add(txtDiaChi, java.awt.BorderLayout.CENTER);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setPreferredSize(new java.awt.Dimension(108, 31));
        jPanel8.add(btnDelete, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel8);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-First-icon-48.png"))); // NOI18N
        jPanel10.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fast-backward-icon-48.png"))); // NOI18N
        jPanel10.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Forward-icon-48.png"))); // NOI18N
        jPanel10.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Last-icon-48.png"))); // NOI18N
        jPanel10.add(jButton9);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jtableStudent.setModel(studentModelTable);
        jtableStudent.setRowSelectionAllowed(true);
        jtableStudent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtableStudent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtableStudent);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btnGroupSex;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jtableStudent;
    private javax.swing.JPanel pnEmailSDT;
    private javax.swing.JPanel pnMa;
    private javax.swing.JPanel pnTen;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSoDT;
    // End of variables declaration//GEN-END:variables
}
