/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dlu.edu.bai04;

import java.awt.Container;

/**
 *
 * @author coder6622
 */
public class bai04 extends javax.swing.JFrame implements ICaculations {

    /**
     * Creates new form bai04
     */
    private Sign sign;
    private double toBeCalculatedValue;

    public bai04() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnResult = new javax.swing.JPanel();
        txtResult = new javax.swing.JTextField();
        jpnBtn = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnRemainder = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnMotPhanX = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btnDoiDau = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casio");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jpnLabel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 8));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CASIO");
        jpnLabel.add(jLabel1);

        getContentPane().add(jpnLabel, java.awt.BorderLayout.NORTH);

        jpnResult.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

        txtResult.setEditable(false);
        txtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpnResultLayout = new javax.swing.GroupLayout(jpnResult);
        jpnResult.setLayout(jpnResultLayout);
        jpnResultLayout.setHorizontalGroup(
            jpnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnResultLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jpnResultLayout.setVerticalGroup(
            jpnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnResultLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jpnResult, java.awt.BorderLayout.LINE_START);

        jpnBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        jpnBtn.setLayout(new javax.swing.BoxLayout(jpnBtn, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 8, 1));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 16, 8));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel5.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel5.add(btn2);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel5.add(btn3);

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        jPanel5.add(btnDivide);

        btnSqrt.setText("sqrt");
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });
        jPanel5.add(btnSqrt);

        jpnBtn.add(jPanel5);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 8, 1));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 16, 8));

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel4.add(btn4);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel4.add(btn5);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel4.add(btn6);

        btnMulti.setText("*");
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        jPanel4.add(btnMulti);

        btnRemainder.setText("%");
        btnRemainder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemainderActionPerformed(evt);
            }
        });
        jPanel4.add(btnRemainder);

        jpnBtn.add(jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 8, 1));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 16, 8));

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel6.add(btn7);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel6.add(btn8);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel6.add(btn9);

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd);

        btnMotPhanX.setText("1/x");
        btnMotPhanX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotPhanXActionPerformed(evt);
            }
        });
        jPanel6.add(btnMotPhanX);

        jpnBtn.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 8, 1));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 16, 8));

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel7.add(btn0);

        btnDoiDau.setText("+/-");
        btnDoiDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiDauActionPerformed(evt);
            }
        });
        jPanel7.add(btnDoiDau);

        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel7.add(btnClear);

        btnSub.setText("-");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        jPanel7.add(btnSub);

        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel7.add(btnEqual);

        jpnBtn.add(jPanel7);

        getContentPane().add(jpnBtn, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txtResult.setText(txtResult.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtResult.setText(txtResult.getText() + "2");

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtResult.setText(txtResult.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txtResult.setText(txtResult.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txtResult.setText(txtResult.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtResult.setText(txtResult.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txtResult.setText(txtResult.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txtResult.setText(txtResult.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtResult.setText(txtResult.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txtResult.setText(txtResult.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDoiDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiDauActionPerformed
        String value = txtResult.getText();
        if (!value.contains("-")) {
            txtResult.setText("-" + value);
        } else {
            try {
                txtResult.setText(value.split("-")[1]);

            } catch (IndexOutOfBoundsException ex) {
                txtResult.setText("");
            }

        }
    }//GEN-LAST:event_btnDoiDauActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        sign = Sign.divide;
        if (txtResult.getText().length() > 0) {
            toBeCalculatedValue = Double.parseDouble(txtResult.getText());
            txtResult.setText("");
        }

    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        sign = Sign.multiply;
        if (txtResult.getText().length() > 0) {
            toBeCalculatedValue = Double.parseDouble(txtResult.getText());
            txtResult.setText("");
        }


    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        sign = Sign.add;
        if (txtResult.getText().length() > 0) {
            toBeCalculatedValue = Double.parseDouble(txtResult.getText());
            txtResult.setText("");
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        sign = Sign.sub;
        if (txtResult.getText().length() > 0) {
            toBeCalculatedValue = Double.parseDouble(txtResult.getText());
            txtResult.setText("");
        }


    }//GEN-LAST:event_btnSubActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        sign = Sign.sqrt;
        if (txtResult.getText().length() > 0) {
            toBeCalculatedValue = Double.parseDouble(txtResult.getText());
            txtResult.setText("");
        }


    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnRemainderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemainderActionPerformed
        sign = Sign.chiaDu;
        if (txtResult.getText().length() > 0) {
            toBeCalculatedValue = Double.parseDouble(txtResult.getText());
            txtResult.setText("");
        }


    }//GEN-LAST:event_btnRemainderActionPerformed

    private void btnMotPhanXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotPhanXActionPerformed
        sign = Sign.tinh1PhanX;
        if (txtResult.getText().length() > 0) {
            toBeCalculatedValue = Double.parseDouble(txtResult.getText());
            txtResult.setText("");
        }


    }//GEN-LAST:event_btnMotPhanXActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed

        if (txtResult.getText().length() > 0) {
            double b = Double.parseDouble(txtResult.getText());
            switch (sign) {
                case add -> {
                    add(toBeCalculatedValue, b);
                }
                case sub -> {
                    subtract(toBeCalculatedValue, b);
                }
                case multiply -> {
                    multiply(toBeCalculatedValue, b);
                }
                case divide -> {
                    divide(toBeCalculatedValue, b);
                }
                case sqrt -> {
                    sqrt(b);
                }
                case chiaDu -> {
                    chiaLayDu(toBeCalculatedValue, b);
                }
                case tinh1PhanX -> {
                    caculate1DivideX(b);
                }
                default ->
                    throw new AssertionError();
            }
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDoiDau;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMotPhanX;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnRemainder;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jpnBtn;
    private javax.swing.JPanel jpnLabel;
    private javax.swing.JPanel jpnResult;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables

    private void setResult(String result) {
        txtResult.setText(result);
    }

    @Override
    public void add(double a, double b) {
        setResult(String.valueOf(a + b));
    }

    @Override
    public void subtract(double a, double b) {
        setResult(String.valueOf(a - b));
    }

    @Override
    public void multiply(double a, double b) {
        setResult(String.valueOf(a * b));
    }

    @Override
    public void divide(double a, double b) {
        setResult(String.valueOf(a / b));
    }

    @Override
    public void chiaLayDu(double a, double b) {
        setResult(String.valueOf(a % b));
    }

    @Override
    public void sqrt(double a) {
        setResult(String.valueOf(Math.sqrt(a)));
    }

    @Override
    public void caculate1DivideX(double x) {
        setResult(String.valueOf(1 / x));
    }

}
