/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coder6622.view;

import com.coder6622.model.Product;
import com.coder6622.model.ProductDAO;
import com.coder6622.model.ProductTableModel;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author coder6622
 */
public class ProductView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ProductTableModel tableModel;

    public ProductView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableProduct = new javax.swing.JTable();
        jpnForm = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcboDvt = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNhaCungCap = new javax.swing.JTextField();
        jpnBtn = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpnTable.setBackground(new java.awt.Color(255, 153, 51));
        jpnTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sach San Pham", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(255, 0, 255))); // NOI18N
        jpnTable.setForeground(new java.awt.Color(255, 51, 51));
        jpnTable.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));

        tableModel = new ProductTableModel();
        jtableProduct.setModel(tableModel);
        jScrollPane1.setViewportView(jtableProduct);

        jpnTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpnTable, java.awt.BorderLayout.PAGE_START);

        jpnForm.setBackground(new java.awt.Color(255, 204, 204));
        jpnForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jpnForm.setLayout(new java.awt.GridLayout(1, 2, 16, 16));

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ma San Pham");
        jPanel2.add(jLabel1);
        jPanel2.add(txtId);

        jPanel7.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ten san pham");
        jPanel3.add(jLabel2);
        jPanel3.add(txtTen);

        jPanel7.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Don Vi Tinh");
        jPanel6.add(jLabel3);

        jcboDvt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chai", "Thung", "Lon", "Kg" }));
        jPanel6.add(jcboDvt);

        jPanel7.add(jPanel6);

        jpnForm.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        jPanel9.setBackground(new java.awt.Color(255, 204, 204));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Don Gia");
        jPanel9.add(jLabel4);
        jPanel9.add(txtDonGia);

        jPanel8.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nha cung cap");
        jPanel10.add(jLabel5);
        jPanel10.add(txtNhaCungCap);

        jPanel8.add(jPanel10);

        jpnForm.add(jPanel8);

        getContentPane().add(jpnForm, java.awt.BorderLayout.CENTER);

        jpnBtn.setBackground(new java.awt.Color(102, 255, 51));
        jpnBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));

        btnAdd.setText("Them San Pham");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jpnBtn.add(btnAdd);

        btnEdit.setText("Chinh Sua Thong Tin");
        jpnBtn.add(btnEdit);

        btnDelete.setText("Xoa San Pham");
        jpnBtn.add(btnDelete);

        getContentPane().add(jpnBtn, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://djpnBtn.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductView().setVisible(true);
            }
        });
    }

    public void setTableModel(ProductTableModel tableModel) {
        jtableProduct.setModel(tableModel);
    }

    public void addAddProductListener(ActionListener listener) {
        btnAdd.addActionListener(listener);
    }

    public void addEditProductListener(ActionListener listener) {
        btnEdit.addActionListener(listener);
    }

    public void addDeleteProductListener(ActionListener listener) {
        btnDelete.addActionListener(listener);
    }

    public void addTableSelectionListener(ListSelectionListener listener) {
        jtableProduct.getSelectionModel().addListSelectionListener(listener);
    }

    public void showListProduct(List<Product> products) {
//        ProductDAO productDAO = new ProductDAO();
//        List<Product> products = productDAO.getProducts();
        tableModel.setData(products);
    }

    private boolean validateProductData(String name, int quantity) {
        if (name.length() == 0 || quantity == 0) {
            return false;
        }

        return true;
    }

    public Product getProductData() {

        String maSP = txtId.getText();

        String name = txtTen.getText();

        String dvt = jcboDvt.getSelectedItem().toString();

        int giaBan = 0;

        try {
            giaBan = Integer.parseInt(txtDonGia.getText());
        } catch (NumberFormatException ex) {
        }
        String nhaCungCap = txtNhaCungCap.getText();

//        if (validateProductData(name, quantity) == false) {
//            showMessage("Thông tin không hợp lệ!");
//            return null;
//        }
        Product product = new Product(maSP, name, dvt, giaBan, nhaCungCap);

        return product;
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void fillInputForm() {
        int row = jtableProduct.getSelectedRow();

        if (row >= 0) {
            txtId.setText(jtableProduct.getValueAt(row, 0).toString());
            txtTen.setText(jtableProduct.getValueAt(row, 1).toString());
            jcboDvt.setSelectedItem(jtableProduct.getValueAt(row, 2).toString());
            txtDonGia.setText(jtableProduct.getValueAt(row, 3).toString());
            txtNhaCungCap.setText(jtableProduct.getValueAt(row, 4).toString());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcboDvt;
    private javax.swing.JPanel jpnBtn;
    private javax.swing.JPanel jpnForm;
    private javax.swing.JPanel jpnTable;
    private javax.swing.JTable jtableProduct;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
